Add tests for template server
modelcontextprotocol/create-python-server pull request #7
Opened 2024-11-27 05:44 UTC by jtorreggiani

Implements a basic test template that invokes all of the server methods end-to-end using an stdio client to the template.

Including a test in the template is useful both for end users and developers contributing to the project. When changes are made to core templates, the tests can be run on the test server to ensure things are running correctly.

2024-11-29 05:48 UTC, darinkishore approved these changes
lgtm! Would be great to have this in the default implementation.

2024-11-29 05:49 UTC, darinkishore commented
@jspahrsummers @dsp-ant 

would be great to get this merged if it looks okay to yall !

2024-11-29 19:46 UTC, dsp-ant requested changes
Thank you for your proposal.

I don't think we necessarily want to test the end-to-end flow. This would make a lot of assumptions about the environment that are easy enough to break.

Notable, the server is meant as a starting point. People will inherently edit it and instantly break the tests. I think for now I am more comfortable not including any tests.

2024-11-29 19:46 UTC, dsp-ant commented on src/create_mcp_server/__init__.py
> +        ("test_server.py.jinja2", "test_server.py", target_dir),
I don't think this is the right directory tests should live. This would entangle them with the package.

2024-11-29 19:46 UTC, dsp-ant commented on src/create_mcp_server/template/test_server.py.jinja2
> +        command=f"{test_dir}/template_server/src/template_server/server.py",
This path assumes that the server is called template_server, which does not hold true..

2024-11-29 19:46 UTC, closed without merging

2024-11-30 21:15 UTC, jtorreggiani commented
> Thank you for your proposal.
> 
> I don't think we necessarily want to test the end-to-end flow. This would make a lot of assumptions about the environment that are easy enough to break.
> 
> Notable, the server is meant as a starting point. People will inherently edit it and instantly break the tests. I think for now I am more comfortable not including any tests.

Thanks @dsp-ant  the consideration here. I think idea for these tests is to ensure that the started server actually will run. I generated the template and it did not work out the of the box. There we implementation details in the template that were not documented. Without tests I think it will be easy for these template code to become out of date or break when changes are made without knowing.

Perhaps tests could be added to the repository itself and a they can be run against an instance of a test server generated with the tool?